### ISSUE TITLE
fairseq/clib/libbleu/libbleu.cpp:10:10: fatal error: 'array' file not found

### ISSUE THREAD

**Issue by gitmcdull** [facebookresearch/fairseq-py#135]
I have successfully installed pytorch 0.4.0. on mac.
>>> import torch
>>> print(torch.__version__)
0.4.0a0+0b17f4b

But I got an error when I type "python setup.py build". How to fix it?
running build
running build_py
running build_ext
building 'fairseq.libbleu' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/q/anaconda/envs/python36/include -arch x86_64 -I/Users/q/anaconda/envs/python36/include -arch x86_64 -I/Users/q/anaconda/envs/python36/include/python3.6m -c fairseq/clib/libbleu/libbleu.cpp -o build/temp.macosx-10.7-x86_64-3.6/fairseq/clib/libbleu/libbleu.o -std=c++11
fairseq/clib/libbleu/libbleu.cpp:10:10: fatal error: 'array' file not found
#include <array>
         ^
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by gitmcdull** [comment]
Fixed. Added '-mmacosx-version-min=10.11' to extra_compile_args in setup.py.
    extra_compile_args=['-std=c++11', '-mmacosx-version-min=10.11'],

**Comment by kingjr** [comment]
Still encountered error on my mac

changing `libbleu.cppp'

```#include <array>``` =>  ```#include <tr1/array>``` fixed it for me

**Comment by liezl200** [comment]
This happened for me when running `pip install fairseq` on my Mac. I ran `export CFLAGS='-stdlib=libc++` and then `pip install fairseq` completed successfully.
